### ISSUE TITLE
Model collapse

### ISSUE THREAD

**Issue by TrueNobility303** [hao-ai-lab/Consistency_LLM#11]
Hi!

Dear authors,

Thanks for your excellent work! 
I train the CLLM model on GSM8k with Abel-7B-001 as the teacher model, using the dataset 
`cleaned_gsm8k_jacobi` dataset you provided on hugginface, and run the train_cllm.sh with n_token_seq_size=16.
Now the training process has been completed 1/5, but the checkpoint does not look good. It seems that the model has collapsed to output the same tokens, as shown in the following picture.

![image](https://github.com/hao-ai-lab/Consistency_LLM/assets/78390095/efeaa692-8a3a-4334-bebf-d7816020de1c)

Is this phenomenon normal? Did I use the training scripts correctly?

I would greatly appreciate it if you could help me. 

Best regards.

**Comment by w32zhong** [comment]
Might be relevant to my observations as well. See https://github.com/hao-ai-lab/Consistency_LLM/issues/4

**Comment by TrueNobility303** [comment]
> Might be relevant to my observations as well. See #4

Thanks a lot.

**Comment by snyhlxde1** [comment]
Hi, thank you for your interest in our work! Did it happen a lot over a wide range of queries after training or just a small number? 

In our experiments, we also observed that CLLMs' performance is highly related to both the pre-trained model and Jacobi trajectories' quality. So data pre-processing before training to clean up token-level and sentence-level repetition is needed. For some small subset of queries, generation quality might not be as good because of both Jacobi trajectories' quality and reasons mentioned in https://github.com/hao-ai-lab/Consistency_LLM/issues/4.

At the time our math CLLM is trained, Abel-7B-001 is the latest model. Now there is a more recent math-solving model released by the same team and it's significantly stronger: https://huggingface.co/GAIR/Abel-7B-002. I think it's worthy trying.

**Comment by TrueNobility303** [comment]
> Hi, thank you for your interest in our work! Did it happen a lot over a wide range of queries after training or just a small number?
> 
> In our experiments, we also observed that CLLMs' performance is highly related to both the pre-trained model and Jacobi trajectories' quality. So data pre-processing before training to clean up token-level and sentence-level repetition is needed. For some small subset of queries, generation quality might not be as good because of both Jacobi trajectories' quality and reasons mentioned in #4.
> 
> At the time our math CLLM is trained, Abel-7B-001 is the latest model. Now there is a more recent math-solving model released by the same team and it's significantly stronger: https://huggingface.co/GAIR/Abel-7B-002. I think it's worthy trying.

Greatly thanks for your response. It t happens a lot over a wide range of queries. I would finish the whole training procedure to see whether it would be better.
I use the default setting in the code for training one epochs. Is it the right training time?
Also, I wonder whether the checkpoint [cllm/consistency-llm-7b-math](https://huggingface.co/cllm/consistency-llm-7b-math) is trained with the default hyper-parameters?

**Comment by snyhlxde1** [comment]
If it happens a lot over a wide range of queries then something is off. After the training completes, you can test its performance with our evaluation script on GSM8K and compare with our checkpoints to see whether their performance are comparable. 

Regarding the hyper-parameters, we will double check and get back to you.

**Comment by TrueNobility303** [comment]
Thanks a lot for your reply! I will keep trying.

**Comment by TrueNobility303** [comment]
I think I may have found the reason. The "use_gt_labels" in the file `train_cllm_global` should be set to **False**, instead of the default setting of **True**. After this modification, it the training becomes good.
