### ISSUE TITLE
Reproduce Table 1 by this repo?

### ISSUE THREAD

**Issue by dreaming-panda** [hao-ai-lab/Consistency_LLM#6]
Hello, thanks for your nice work.

I want to reproduce table1 (i.e. the accuracy of GSM8k and ShareGPT) but I cannot find scripts to do this.

Could you point me a way?

Thank you!

**Comment by snyhlxde1** [comment]
Thanks for your interests in our work! For table 1, We follow the same settings in [human-eval](https://github.com/openai/human-eval), [Spider](https://github.com/taoyds/spider), [MT-bench](https://github.com/lm-sys/FastChat/tree/main/fastchat/llm_judge) and [GSM8K](https://github.com/openai/grade-school-math) to evaluate CLLMs' generation quality, but with Jacobi decoding instead of conventional AR decoding. 

Output generation code for gsm8k and ShareGPT (using Jacobi decoding) have just been upload under the `eval/gsm8k` and `eval/mt-bench` directory. You can use the script to generate outputs and follow [MT-bench](https://github.com/lm-sys/FastChat/tree/main/fastchat/llm_judge)'s instruction to complete the evaluation.

**Comment by dreaming-panda** [comment]
Thank you for your patient response!

**Comment by agentup** [comment]
Thanks for your good work.

I tried to run the gsm8k scripts to reproduce Table 1 results. However, I got the final results as shown in the figure. 
<img width="960" alt="微信图片_20240517091703" src="https://github.com/hao-ai-lab/Consistency_LLM/assets/148850190/5184b865-8f6d-44e0-94a4-e2af9da5e91c">
The performance of CLLM with Jacobi is much lower. 

Do you have any idea where I have made a mistake. Thanks a lot.

**Comment by snyhlxde1** [comment]
@agentup could you provide some more information about your settings? what hardware are you running on and what command arguments did you use?

**Comment by snyhlxde1** [comment]
I noticed you are using `max_new_tokens= 512`, this could be the cause of why you are not getting speedup: you are using a n-token sequence of size 512 for iteration and it could introduce a lot of compute overhead. For GSM8K, please change `max_new_tokens` to 16 or 32 for a significant speedup.

Notice that in this repo, the command arguments has the following meaning:
`max_new_tokens`: n-token sequence size for Jacobi trajectory generation.
`max_seq_len`: your total model generation length.

**Comment by agentup** [comment]
> I noticed you are using `max_new_tokens= 512`, this could be the cause of why you are not getting speedup: you are using a n-token sequence of size 512 for iteration and it could introduce a lot of compute overhead. For GSM8K, please change `max_new_tokens` to 16 or 32 for a good speedup.
> 
> Notice that in this repo, the command arguments has the following meaning: `max_new_tokens`: n-token sequence size for Jacobi trajectory generation. `max_seq_len`: your total model generation length.

Thanks for your help. The problem has been solved.

**Comment by zhihanyang2022** [comment]
I also have issues getting the reported speedup with the correct `max_new_tokens=16`. Here's the command I used: `CUDA_VISIBLE_DEVICES=0 bash eval/gsm8k/speedup.sh cllm/consistency-llm-7b-math cllm/consistency-llm-7b-math 16`.

<img width="713" height="72" alt="Image" src="https://github.com/user-attachments/assets/fe1e9261-113c-4df5-95fc-7a286c0977db" />
